### ISSUE TITLE
Convert .sql file to a .db file.

### ISSUE THREAD

**Issue by ander2300** [ST-DDT/CommandHelper-CrazyLogin#1]
Hi, I have installed crazylogin with MySQL and now I need to change to a flatfile.

Anyone know how to do this?

Many Thanks

**Comment by ST-DDT** [comment]
This issues belongs to [CrazyLogin](https://github.com/ST-DDT/CrazyLogin).

Steps to convert your sql database to a flat one:
* Connect to your database server using an admin tool
* Execute the following request without limit
````sql
SELECT CONCAT(name, '|', password , '|', ips, '|', DATE_FORMAT(lastAction, '%Y-%c-%d %T'), '|', loginFails, '|', if(passwordExpired=0, 'false', 'true')) as entry FROM CrazyLogin_accounts
````
* Save the results in a new file called: `accounts.db`
* Add this line at the beginning of the file: `name|password|ips|lastAction|loginFails|passwordExpired`
* Your file should now look like this:
````txt
name|password|ips|lastAction|loginFails|passwordExpired
User1|05a671c846514124cc08b76ea6d30bb|127.0.0.1|2017-01-01 19:32:51|0|false
User2|ab656514164684688468a4b8684a84|15.1.0.1|2017-02-01 19:32:51|0|false
User3|de8743509384759084357987349587|31.0.1.1|2017-03-01 19:32:51|0|false
User4|908745983745098734509834758345|129.1.1.1|2017-04-01 19:32:51|0|false
User5|fff84750934850984790847509875|250.83.255.1|2017-04-14 19:32:51|0|false
````
* Copy that file to your CrazyLogin plugin directory and set the database type to FLAT in your config.

I hope this solves your issue.

**Comment by ander2300** [comment]
Could you explain a little bit more, plis? How can I save the results in the file accounts.db?

Many Thanks

**Comment by ST-DDT** [comment]
Which tool do you use to manage your database? Console, phpMyAdmin...?

**Comment by ander2300** [comment]
I use MySQL and I also have phpMyAdmin.

Many Thanks

**Comment by ST-DDT** [comment]
MySQL is your database. But how do you access it as human? Do you have a website where you can execute SQL like phpMyAdmin? Or do you have a terminal/shell/command prompt to connect to your database? Can you execute applications on your server or local computer like SquirrelSQL? Or can you only connect to your database via minecraft plugins?

**Comment by ander2300** [comment]
I have a terminal and also phpMyAdmin installed. I can manage the database in this two ways.

Thanks

**Comment by ST-DDT** [comment]
[This question/answer on stackoverflow](https://stackoverflow.com/questions/6332994/write-results-of-sql-query-to-a-file-in-mysql) explains how you can do it using the terminal.
IIRC there is a "export" button in phpmyadmin somewhere in the sql/result-screen, but i'm not sure about this variant.
